### ISSUE TITLE
Google Cloud integration

### ISSUE THREAD

**Issue by lfrancke** [stackabletech/t2#177]
- [x] research
- [x] T2 API user and project setup in Google Cloud (@teozkr did the work here)
- [x] create a first (draft) Terraform file w/ fixed values for region/zone, K8s version, node count and node size, ...
- [x] add the Stackable/Ansible part (copy over from other mK8s)
- [x] set K8s version in cluster config (currently 1.21.x .. 1.24.x available, 1.22.x is the default)
- [x] set region/zone/location in cluster config
- [x] set cluster sizing in cluster config - can this be done using the default node pool or do we need a separate node pool?
- [x] check if quotas are sufficient
- [x] Are all the labels set to feed the cluster info file?
- [x] Dev deployment
- [x] Test the cluster creation in the dev deployment
- [x] first PR: #374 
- [x] provide credentials for testdriver (see task #329)
- [x] Add test cluster def to CI tests and let Jenkins run the cluster
- [x] Check if we could isolate the cluster-specific dynamically created cluster-admin-accounts (see comment) (postponed to #378)
- [x] At least: reduce credentials of cluster admin to K8s stuff
- [x] Check if the cluster-admin-accounts are able to delete/resize the whole cluster (not any more after creation of role `roles/t2.cluster.admin`)
- [x] docs in "using T2"
- [x] `WARNING: the gcp auth plugin is deprecated in v1.22+, unavailable in v1.26+; use gcloud instead.` https://github.com/stackabletech/t2/pull/380
- [x] Have a look at private cluster stuff (see comment). Do we need this?

**Comment by backstreetkiwi** [comment]
Links
* Authentication/Tokens: https://cloud.google.com/docs/authentication?_ga=2.201684497.-1654663789.1654112780

**Comment by backstreetkiwi** [comment]
In the current state of development, the dynamically created cluster-admin service accounts are able to access all clusters because there is no separation because the roles are all on project-level: https://cloud.google.com/iam/docs/understanding-roles#kubernetes-engine-roles.
Maybe something which we do *inside* Kubernetes (RBAC) could solve that problem and help us to further isolate the users. Maybe there are some valuable hints here: https://cloud.google.com/kubernetes-engine/docs/how-to/kubernetes-service-accounts
